language: php
dist: xenial

php:
  - '7.1'

install: travis_retry composer update --prefer-dist

script: phpunit --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
